---
jobs:
- name: push-riemann-firehose-nozzle
  plan:
  - aggregate:
    - get: riemann-firehose-nozzle-app
      trigger: true
  - put: deploy-riemann-firehose-nozzle-app
    params:
      manifest: riemann-firehose-nozzle-app/manifest.yml
      path: riemann-firehose-nozzle-app
      current_app_name: riemann-firehose-nozzle
      environment_variables:
        NOZZLE_RIEMANN_HOST: {{riemann-host}}
        NOZZLE_RIEMANN_PORT: {{riemann-port}}
        NOZZLE_RIEMANN_TRANSPORT: {{riemann-transport}}
        NOZZLE_METRICPREFIX: {{metric-prefix}}
        NOZZLE_UAAURL: {{uaa-url}}
        NOZZLE_USERNAME: {{username}}
        NOZZLE_PASSWORD: {{password}}
        NOZZLE_INSECURESSLSKIPVERIFY: {{insecure-ssl-skip-verify}}
        NOZZLE_TRAFFICCONTROLLERURL: {{traffic-controller-url}}
        NOZZLE_DEPLOYMENT: {{cf-deployment}}

    on_failure:
      put: slack
      params:
        text: |
          :x: FAILED to deploy riemann-firehose-nozzle on production
          <$ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}
    on_success:
      put: slack
      params:
        text: |
          :white_check_mark: Successfully deployed riemann-firehose-nozzle on production
          <$ATC_EXTERNAL_URL/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME|View build details>
        channel: {{slack-channel}}
        username: {{slack-username}}
        icon_url: {{slack-icon-url}}

resources:
- name: riemann-firehose-nozzle-app
  type: git
  source:
    uri: {{riemann-firehose-nozzle-app-git-url}}
    branch: {{riemann-firehose-nozzle-app-git-branch}}

- name: deploy-riemann-firehose-nozzle-app
  type: cf
  source:
    api: {{cf-api-url}}
    username: {{cf-deploy-username}}
    password: {{cf-deploy-password}}
    organization: {{cf-organization}}
    space: {{cf-space}}
    skip_cert_check: false

- name: slack
  type: slack-notification
  source:
    url: {{slack-webhook-url}}

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
